### ISSUE TITLE
When add dearImgui to renderable other renderables dont draw

### ISSUE THREAD

**Issue by geotyper** [electromaggot/HelloVulkanSDL#3]
When add dearImgui to renderable other renderables dont draw
![Screenshot at 2022-02-20 17-58-30](https://user-images.githubusercontent.com/30755433/154849040-94e14034-3812-4642-95f7-37b3624c1879.png)

if comment  vulkan.command.renderables.Add(dearImgui);
examples render normal

**Comment by geotyper** [comment]
find solution but think this is wrong| but draw ImGui and example 
![Screenshot at 2022-02-20 19-26-33](https://user-images.githubusercontent.com/30755433/154852965-9cf5c320-0af6-4297-97a5-39936605ee90.png)

add all as renderables.Add(DynamicRenderable(demos[iDemoMode], vulkan, platform));

**Comment by geotyper** [comment]
![Screenshot at 2022-02-20 19-28-42](https://user-images.githubusercontent.com/30755433/154853036-fc00715e-ce21-4f91-bc53-150a900945e0.png)
looks like this/ but if resize window/ program crashed

**Comment by electromaggot** [comment]
I'm glad you got this working (so long ago!).  As for the crash, it's probably fixed by now, after much testing was done to shore-up window resize and the `Recreate` process (where Vulkan components must be destroyed then created again).

As for Dear ImGui, I did add support for it in [VulkanModule/Platform/GUISystem](https://github.com/electromaggot/VulkanModule/tree/master/Platform/GUISystem) along with instructions there on how to "activate" it.  However, since I was trying to keep this project HelloVulkanSDL *lightweight* &ndash; it being a "hello world" program & all &ndash; it only includes the "stubs" for the ImGui support.  (Those are designed to be easily "drop-in replaced" with Dear ImGui files however.)

The [VulkanAddOns](https://github.com/electromaggot/VulkanAddOns) project is more advanced and includes better support for (actually will be made to require) Dear ImGui.  Please try out that repository.
Because of these points, I'm closing this issue.
