### ISSUE TITLE
How to update VertexBuffer

### ISSUE THREAD

**Issue by geotyper** [electromaggot/HelloVulkanSDL#4]
Try like this, but have runtime error
![Screenshot at 2022-05-10 10-49-08](https://user-images.githubusercontent.com/30755433/167577740-3ffc4474-34cd-447d-bccf-4d1de795bcd6.png)
Do you have some idea why issue runtime error?

**Comment by geotyper** [comment]
find error: array of Vertex2DTextured was const array, now vertex coordinates changes, but not update in GPU memory.
If I do with pRenderable->Recreate(vulkan, true), gpu vertex changed coordinates but screen began blink

**Comment by electromaggot** [comment]
The project has evolved extensively since this issue (my sincere apologies, geotyper!) but if anyone else encounters a similar problem, please resubmit as a new issue.
In the changes since, every `Recreate` procedure was tested thoroughly on each supported platform, especially to tear-down and create-anew the hierarchy of Vulkan objects when events occur like window resize, move to another monitor, or switching the graphics device.  On platforms supporting Validation Extensions (Windows, Ubuntu) the VulkanModule was fixed to eliminate Validation Errors.

Also, in the code given above, `DynamicRenderable` is used.  Try instead using `FixedRenderable` since the "dynamic" feature -- where a Renderable's CommandBuffer was to be re-recorded if the object changed -- was (and is still) experimental.  That will be addressed, however, and soon.  Also try the [VulkanAddOns](https://github.com/electromaggot/VulkanAddOns) project if you have trouble; it may demonstrate what you're trying to do more clearly.
In the meantime I will close this issue.
